# Generated by Django 5.1.7 on 2026-06-19 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Administrator', '0001_initial'),
        ('Guest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_activity',
            fields=[
                ('activity_id', models.AutoField(primary_key=True, serialize=False)),
                ('activity_name', models.CharField(max_length=100)),
                ('activity_description', models.TextField()),
                ('activity_credit', models.IntegerField()),
                ('activity_startdate', models.DateField()),
                ('activity_enddate', models.DateField()),
                ('activity_file', models.FileField(blank=True, null=True, upload_to='Assets/ActivityDocs/')),
                ('activity_status', models.IntegerField(default=0)),
                ('activity_date', models.DateField(auto_now_add=True)),
                ('activitycategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administrator.tbl_activitycategory')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_faculty')),
            ],
        ),
    ]
