# Generated by Django 5.1.7 on 2026-06-19 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_activitycategory',
            fields=[
                ('activitycategory_id', models.AutoField(primary_key=True, serialize=False)),
                ('activitycategory_name', models.CharField(max_length=100)),
                ('activitycategory_description', models.TextField()),
                ('activitycategory_status', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_adminregistration',
            fields=[
                ('adminregistration_id', models.AutoField(primary_key=True, serialize=False)),
                ('adminregistration_name', models.CharField(max_length=60)),
                ('adminregistration_contact', models.CharField(max_length=60)),
                ('adminregistration_email', models.CharField(max_length=60, unique=True)),
                ('adminregistration_password', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_auditlog',
            fields=[
                ('auditlog_id', models.AutoField(primary_key=True, serialize=False)),
                ('auditlog_usertype', models.CharField(max_length=20)),
                ('auditlog_userid', models.IntegerField()),
                ('auditlog_module', models.CharField(max_length=50)),
                ('auditlog_action', models.CharField(max_length=255)),
                ('auditlog_date', models.DateField(auto_now_add=True)),
                ('auditlog_time', models.TimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_creditmaster',
            fields=[
                ('creditmaster_id', models.AutoField(primary_key=True, serialize=False)),
                ('creditmaster_category', models.CharField(max_length=50)),
                ('creditmaster_credit', models.IntegerField()),
                ('creditmaster_status', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_department',
            fields=[
                ('department_id', models.AutoField(primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=100)),
                ('department_status', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_notification',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('notification_title', models.CharField(max_length=100)),
                ('notification_content', models.TextField()),
                ('notification_role', models.CharField(max_length=20)),
                ('notification_date', models.DateField(auto_now_add=True)),
                ('notification_status', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_programme',
            fields=[
                ('programme_id', models.AutoField(primary_key=True, serialize=False)),
                ('programme_name', models.CharField(max_length=100)),
                ('programme_duration', models.IntegerField()),
                ('programme_totalcredit', models.IntegerField()),
                ('programme_status', models.IntegerField(default=1)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administrator.tbl_department')),
            ],
        ),
    ]
