# Generated by Django 5.1.7 on 2026-06-25 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Administrator', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_auditlog',
        ),
    ]
