# Generated by Django 5.1.7 on 2026-06-19 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Faculty', '0001_initial'),
        ('Guest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_activityregistration',
            fields=[
                ('activityregistration_id', models.AutoField(primary_key=True, serialize=False)),
                ('activityregistration_date', models.DateField(auto_now_add=True)),
                ('activityregistration_status', models.IntegerField(default=0)),
                ('activityregistration_completionstatus', models.IntegerField(default=0)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Faculty.tbl_activity')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_student')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_certificate',
            fields=[
                ('certificate_id', models.AutoField(primary_key=True, serialize=False)),
                ('certificate_title', models.CharField(max_length=100)),
                ('certificate_file', models.FileField(upload_to='Assets/StudentCertificates/')),
                ('certificate_credit', models.IntegerField(default=0)),
                ('certificate_remark', models.TextField(blank=True, null=True)),
                ('certificate_status', models.IntegerField(default=0)),
                ('certificate_date', models.DateField(auto_now_add=True)),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Faculty.tbl_activity')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_student')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_complaint',
            fields=[
                ('complaint_id', models.AutoField(primary_key=True, serialize=False)),
                ('complaint_title', models.CharField(max_length=100)),
                ('complaint_content', models.TextField()),
                ('complaint_reply', models.TextField(blank=True, null=True)),
                ('complaint_status', models.IntegerField(default=0)),
                ('complaint_date', models.DateField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_student')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_feedback',
            fields=[
                ('feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('feedback_content', models.TextField()),
                ('feedback_reply', models.TextField(blank=True, null=True)),
                ('feedback_date', models.DateField(auto_now_add=True)),
                ('feedback_status', models.IntegerField(default=0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_student')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_internship',
            fields=[
                ('internship_id', models.AutoField(primary_key=True, serialize=False)),
                ('internship_title', models.CharField(max_length=100)),
                ('internship_description', models.TextField()),
                ('internship_startdate', models.DateField(blank=True, null=True)),
                ('internship_enddate', models.DateField(blank=True, null=True)),
                ('internship_status', models.IntegerField(default=0)),
                ('internship_date', models.DateField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_company')),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Guest.tbl_faculty')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_student')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_evaluation',
            fields=[
                ('evaluation_id', models.AutoField(primary_key=True, serialize=False)),
                ('evaluation_marks', models.IntegerField()),
                ('evaluation_remark', models.TextField()),
                ('evaluation_status', models.IntegerField(default=1)),
                ('evaluation_date', models.DateField(auto_now_add=True)),
                ('internship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student.tbl_internship')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_internshiplog',
            fields=[
                ('internshiplog_id', models.AutoField(primary_key=True, serialize=False)),
                ('internshiplog_workdate', models.DateField()),
                ('internshiplog_workdone', models.TextField()),
                ('internshiplog_hours', models.IntegerField()),
                ('internshiplog_remark', models.TextField(blank=True, null=True)),
                ('internshiplog_date', models.DateField(auto_now_add=True)),
                ('internship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student.tbl_internship')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_internshipreport',
            fields=[
                ('internshipreport_id', models.AutoField(primary_key=True, serialize=False)),
                ('internshipreport_file', models.FileField(upload_to='Assets/InternshipReports/')),
                ('internshipreport_certificate', models.FileField(upload_to='Assets/InternshipCertificates/')),
                ('internshipreport_remark', models.TextField(blank=True, null=True)),
                ('internshipreport_status', models.IntegerField(default=0)),
                ('internshipreport_date', models.DateField(auto_now_add=True)),
                ('internship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student.tbl_internship')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_project',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('project_title', models.CharField(max_length=100)),
                ('project_description', models.TextField()),
                ('project_proposal', models.FileField(blank=True, null=True, upload_to='Assets/ProjectProposals/')),
                ('project_report', models.FileField(blank=True, null=True, upload_to='Assets/ProjectReports/')),
                ('project_status', models.IntegerField(default=0)),
                ('project_date', models.DateField(auto_now_add=True)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_faculty')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_student')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_studentcredit',
            fields=[
                ('studentcredit_id', models.AutoField(primary_key=True, serialize=False)),
                ('studentcredit_type', models.CharField(max_length=50)),
                ('studentcredit_sourceid', models.IntegerField()),
                ('studentcredit_credit', models.IntegerField()),
                ('studentcredit_remark', models.CharField(blank=True, max_length=255, null=True)),
                ('studentcredit_date', models.DateField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_student')),
            ],
        ),
    ]
