# Generated by Django 5.1.7 on 2026-06-19 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Administrator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_company',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=100)),
                ('company_contactperson', models.CharField(max_length=100)),
                ('company_email', models.EmailField(max_length=100, unique=True)),
                ('company_contact', models.CharField(max_length=20)),
                ('company_address', models.TextField()),
                ('company_password', models.CharField(max_length=60)),
                ('company_proof', models.FileField(blank=True, null=True, upload_to='Assets/CompanyDocs/')),
                ('company_status', models.IntegerField(default=0)),
                ('company_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_faculty',
            fields=[
                ('faculty_id', models.AutoField(primary_key=True, serialize=False)),
                ('faculty_name', models.CharField(max_length=100)),
                ('faculty_email', models.EmailField(max_length=100, unique=True)),
                ('faculty_contact', models.CharField(max_length=20)),
                ('faculty_address', models.TextField()),
                ('faculty_photo', models.FileField(blank=True, null=True, upload_to='Assets/FacultyDocs/')),
                ('faculty_password', models.CharField(max_length=60)),
                ('faculty_status', models.IntegerField(default=0)),
                ('faculty_date', models.DateField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administrator.tbl_department')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=100)),
                ('student_gender', models.CharField(max_length=20)),
                ('student_dob', models.DateField()),
                ('student_email', models.EmailField(max_length=100, unique=True)),
                ('student_contact', models.CharField(max_length=20)),
                ('student_address', models.TextField()),
                ('student_admissionno', models.CharField(max_length=50, unique=True)),
                ('student_semester', models.IntegerField(default=1)),
                ('student_photo', models.FileField(blank=True, null=True, upload_to='Assets/StudentDocs/')),
                ('student_password', models.CharField(max_length=60)),
                ('student_status', models.IntegerField(default=0)),
                ('student_date', models.DateField(auto_now_add=True)),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administrator.tbl_programme')),
            ],
        ),
    ]
